# Generated by Django 2.1.8 on 2019-05-21 07:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailimages', '0001_squashed_0021'),
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewPostPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('posttitle', models.CharField(max_length=250)),
                ('subheading', models.CharField(max_length=250)),
                ('body', wagtail.core.fields.RichTextField()),
                ('featured_image_caption', models.CharField(blank=True, max_length=250, null=True)),
                ('featured_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
