# Generated by Django 2.1.8 on 2019-05-21 07:37

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailimages', '0001_squashed_0021'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('news', '0002_newpostpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPostPage',
            new_name='NewsPostPage',
        ),
    ]
