# Generated by Django 2.1.8 on 2019-05-15 10:32

import datetime
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('exhibition', '0002_exhibitiondetailpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='exhibitiondetailpage',
            name='artist',
            field=models.CharField(default='Anon.', max_length=250),
        ),
        migrations.AddField(
            model_name='exhibitiondetailpage',
            name='body',
            field=wagtail.core.fields.RichTextField(default=''),
        ),
        migrations.AddField(
            model_name='exhibitiondetailpage',
            name='ending_date',
            field=models.DateField(default=datetime.date(2019, 5, 15), verbose_name='Closing Date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibitiondetailpage',
            name='exhibition_title',
            field=models.CharField(default='Example', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exhibitiondetailpage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='exhibitiondetailpage',
            name='featured_image_caption',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='exhibitiondetailpage',
            name='starting_date',
            field=models.DateField(default=datetime.date(2019, 5, 15), verbose_name='Opening Date'),
            preserve_default=False,
        ),
    ]
