# Generated by Django 2.1.8 on 2019-05-22 04:55

from django.db import migrations, models
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('exhibition', '0004_auto_20190515_1113'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.AddField(
            model_name='exhibitiondetailpage',
            name='artists',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='exhibition.Artist'),
        ),
    ]
