# Generated by Django 2.1.8 on 2019-05-21 09:17

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutgallerypage',
            name='about_page_title',
            field=models.CharField(default='Our Gallery', max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutgallerypage',
            name='body',
            field=wagtail.core.fields.RichTextField(default='Hello'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='aboutgallerypage',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='aboutgallerypage',
            name='location',
            field=models.CharField(default='Thamel', max_length=250),
            preserve_default=False,
        ),
    ]
