# Generated by Django 2.1.8 on 2019-05-22 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopdetailpage',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='workshopdetailpage',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
