# Generated by Django 2.1.8 on 2019-05-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workshop', '0002_auto_20190522_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshopdetailpage',
            name='price',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
